### PR TITLE
Rephrasing README. Introduce citation file

### PR DESCRIPTION
**Pull request by fandreuz**
In this PR I made some minor changes to the README file, like enforcing Python syntax highlighting in code samples. I also introduced `CITATION.cff` which enables the `Cite this repository` option in the right menu in your GitHub repository:

2022-07-02 at 10 41

### CODE REVIEW

**Comment by fAndreuzzi** [comment]
@openjournals/joss-reviews#4534

**Comment by fandreuz** [comment]
This is part of openjournals/joss-reviews#4534

**Comment by fandreuz** [comment]
Please @max-little, check `CITATION.cff` in `Files changed` and fix/complete wrong or missing details. For instance, I'd need the orcid for you and your co-author. I would suggest you reply to this comment with the missing data and I'll update the PR accordingly.

**Comment by max-little** [comment]
Thanks Francesco, very much appreciated. My ORCID is 0000-0002-1507-3822, I
don't think my co-author has one unfortunately. Thanks also for the
suggested changes re citations and the readme, very helpful.

Re: PyTest, we have explored this and from long experience, want to avoid
going down the Python package interdependency route where possible. This is
one downside of OS development e.g. lack of central control over package
quality, and the resulting subtle and not so subtle bugs which arise as a
result. Our preference is to ensure our code is as self-contained as
possible. Of course, that's not always feasible.

PyPi: definitely worth considering at some point in the future, for now we
want to avoid commitments across multiple platforms at this stage.
Hopefully we will see more community buy-in to help with longer term
maintenance.

Best wishes
Max

On Saturday, 2 July 2022, Francesco Andreuzzi ***@***.***>
wrote:
> Please @max-little, check CITATION.cff in Files changed and fix/complete
wrong or missing details. For instance, I'd need the orcid for you and your
co-author. I would suggest you reply to this comment with the missing data
and I'll update the PR accordingly.
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.Message ID:
***@***.***>

-- 
Max Little (www.maxlittle.net)
Associate Professor, University of Birmingham
Turing Fellow, Alan Turing Institute
TED Fellow (fellows.ted.com/profiles/max-little)
Visiting Associate Professor, MIT
Author: Machine Learning for Signal Processing, Oxford University Press
global.oup.com/academic/product/machine-learning-for-signal-processing-9780198714934
Room 138, School of Computer Science
University of Birmingham
Birmingham B15 2TT
UK +44 7710 609564
Skype: dr.max.little

**Pull request merged**
